# Generated by Django 3.2.19 on 2023-08-28 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_store', models.CharField(max_length=100)),
                ('book_title', models.CharField(max_length=100)),
                ('author_info', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.PositiveIntegerField()),
                ('date_publish', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['date_publish'],
            },
        ),
        migrations.CreateModel(
            name='SaveHttpRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=6)),
                ('request_path', models.CharField(max_length=150)),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-request_datetime'],
            },
        ),
    ]
